version: '3.4'

networks: 
  dockersql-network:
    driver: bridge

services:

  boteventmanagement.api:
    image: tuliorezende/boteventmanagement.api
    build:
      context: .
      dockerfile: BotEventTemplate.Api/Dockerfile
    ports:
    - "20000:80"
    depends_on: 
      - sql.database
    networks: 
      - dockersql-network

  sql.database:
    image: microsoft/mssql-server-linux:2017-latest
    ports: 
      - "1401:1433"
    networks: 
      - dockersql-network