version: '3.4'

services:

  boteventmanagement-api:
    image: tuliorezende/boteventmanagement-api
    build:
      context: .
      dockerfile: BotEventTemplate.Api/Dockerfile
    environment:
     ASPNETCORE_ENVIRONMENT: Production
     DefaultConnection: sql-database;Initial Catalog=BotEventManagementDb;User Id=sa;Password=.4\\LSPAehX;Trusted_Connection=false
    ports:
    - "20000:80"

