- apiVersion: v1
  kind: Service
  metadata:
    name: boteventmanagement-api
    labels:
      app: boteventmanagement-api
  spec:
    ports:
    - port: 80
    type: LoadBalancer

- apiVersion: apps/v1beta2
  kind: Deployment
  metadata:
    name: boteventmanagement-api-deployment
  spec:
    strategy: {}
    selector:
      matchLabels:
        app: boteventmanagement-api
    template:
        metadata:
          name: boteventmanagement-api
          labels:
            app: boteventmanagement-api
        spec:
          containers:
          - name: boteventmanagement-api
            image: tuliorezende/boteventmanagement-api
            env:
                - name: ASPNETCORE_ENVIRONMENT
                  value: Production
                - name: DefaultConnection
                  value: "Server=tcp:#{k8s.dbservername}#.database.windows.net,1433;Initial Catalog=#{k8s.dbdatabasename}#;Persist Security Info=False;User ID=#{k8s.dbusername}#;Password=#{k8s.dbpassword}#;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
            args: ["$(ASPNETCORE_ENVIRONMENT) $(DefaultConnection)"]
            ports:
            - containerPort: 80
            resources: {}
  status: {}