apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: boteventmanagement-api
  labels:
    app: boteventmanagement-api
  spec:
    ports:
    - name: "20000"
      port: 20000
      targetPort: 80
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: boteventmanagement-api
  spec:
    strategy: {}
    selector:
      matchLabels:
        app: boteventmanagement-api
    template:
        metadata:
          name: boteventmanagement-api
        spec:
          containers:
          - name: boteventmanagement-api
            image: tuliorezende/boteventmanagement-api
            env:
                - name: ASPNETCORE_ENVIRONMENT
                  value: Production
                - name: DefaultConnection
                  value: sql-database;Initial Catalog=BotEventManagementDb;User Id=sa;Password=.4\\LSPAehX;Trusted_Connection=false
            args: ["$(ASPNETCORE_ENVIRONMENT) $(DefaultConnection)"]
            ports:
            - containerPort: 80
            resources: {}
          restartPolicy: Always
  status: {}
kind: List
metadata: {}