apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: boteventmanagement-api
    labels:
      app: boteventmanagement-api
  spec:
    ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    type: LoadBalancer
  status: {}
- apiVersion: apps/v1beta2
  kind: Deployment
  metadata:
    name: boteventmanagement-api-deployment
  spec:
    strategy: {}
    selector:
      matchLabels:
        app: boteventmanagement-api
    template:
        metadata:
          name: boteventmanagement-api
          labels:
            app: boteventmanagement-api
        spec:
          containers:
          - name: boteventmanagement-api
            image: tuliorezende/boteventmanagement-api
            env:
                - name: ASPNETCORE_ENVIRONMENT
                  value: Production
                - name: DefaultConnection
                  value: "Server=tcp:#{k8s.dbservername}#.database.windows.net,1433;Initial Catalog=#{k8s.dbdatabasename}#;Persist Security Info=False;User ID=#{k8s.dbusername}#;Password=#{k8s.dbpassword}#;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
            args: ["$(ASPNETCORE_ENVIRONMENT) $(DefaultConnection)"]
            ports:
            - name: http
              containerPort: 80
            resources: {}
          restartPolicy: Always
  status: {}
kind: List
metadata: {}